import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";

const resources = {
  en: {
    translation: {
      nav: { home: "Home", track: "Track", services: "Services", support: "Support", reviews: "Reviews", getQuote: "GET A QUOTE", trackNow: "TRACK NOW", signIn: "Sign In", signUp: "Sign Up", signOut: "Sign Out", myAccount: "My Account" },
      hero: {
        tag1: "REAL-TIME GPS TRACKING", tag2: "AIR FREIGHT", tag3: "NATIONWIDE COVERAGE",
        title1_1: "DELIVERING", title1_2: "CERTAINTY", title1_3: "NOT JUST PACKAGES",
        title2_1: "EXPRESS", title2_2: "OVERNIGHT", title2_3: "DELIVERY",
        title3_1: "COAST TO", title3_2: "COAST", title3_3: "IN DAYS",
        desc1: "Live GPS tracking, instant status updates, and full delivery visibility — from pickup to your doorstep.",
        desc2: "Next-day delivery guaranteed by 10:30 AM. Priority air freight with real-time tracking.",
        desc3: "Our fleet of 500+ vehicles delivers to all 50 states with industry-leading reliability.",
        enterTracking: "Enter Tracking Number", trackBtn: "TRACK"
      },
      stats: { packages: "Packages Delivered", onTime: "On-Time Delivery", states: "States Covered", liveTracking: "Live Tracking" },
      quickActions: { trackPackage: "Track a Package", realTimeUpdates: "Real-time updates", getQuote: "Get a Quote", instantPricing: "Instant pricing", schedulePickup: "Schedule Pickup", weComeToYou: "We come to you", servicesGuide: "Services Guide", compareOptions: "Compare options" },
      services: { title: "Our Services", subtitle: "SHIPPING SOLUTIONS", desc: "From same-day express to economy ground, we have the right delivery option for every package.", expressTitle: "Express Overnight", expressDesc: "Next-day delivery guaranteed by 10:30 AM. Priority handling with real-time GPS tracking and signature confirmation.", standardTitle: "Standard Ground", standardDesc: "Reliable 3-5 business day delivery across the continental US. Full tracking and delivery notifications included.", economyTitle: "Economy Saver", economyDesc: "Budget-friendly option with 5-7 business day delivery. Perfect for non-urgent shipments with full tracking.", fastest: "FASTEST", popular: "POPULAR", value: "VALUE", learnMore: "Learn more" },
      freight: { title: "FREIGHT SERVICES", subtitle: "Global Logistics Solutions", airTitle: "Air Freight", airDesc: "Express air cargo worldwide with priority handling and customs clearance.", seaTitle: "Sea Freight", seaDesc: "Cost-effective ocean freight for large shipments with full container tracking.", landTitle: "Land Freight", landDesc: "Reliable ground transportation with nationwide coverage and GPS tracking.", getStarted: "Get Started" },
      features: { realTimeTitle: "LIVE GPS TRACKING ON EVERY PACKAGE", realTimeDesc: "Watch your package move in real time on an interactive map. Our GPS-enabled fleet transmits location updates every 5 seconds.", seeTracking: "SEE LIVE TRACKING", facilityTitle: "STATE-OF-THE-ART SORTING FACILITIES", facilityDesc: "Our network of automated sorting centers processes thousands of packages per hour with 99.9% accuracy.", podTitle: "PROOF OF DELIVERY EVERY TIME", podDesc: "Our drivers capture photo proof at every delivery. Combined with GPS-verified location data and digital signatures, you have complete peace of mind." },
      testimonials: { title: "TRUSTED BY THOUSANDS", seeAll: "SEE ALL REVIEWS" },
      cta: { title: "READY TO SHIP?", desc: "Start tracking your packages today with TransportHaven's industry-leading logistics platform.", trackPackage: "TRACK A PACKAGE", getQuote: "GET A QUOTE" },
      footer: { tagline: "Delivering certainty, not just packages. Real-time logistics for the modern world.", ship: "Ship", company: "Company", support: "Support", trackPackage: "Track Package", getQuote: "Get a Quote", schedulePickup: "Schedule Pickup", serviceGuide: "Service Guide", aboutUs: "About Us", careers: "Careers", press: "Press", sustainability: "Sustainability", faq: "FAQ", reviews: "Reviews", privacy: "Privacy Policy", terms: "Terms of Service", cookies: "Cookie Policy", rights: "All rights reserved." },
      topBar: { trackPackage: "Track a Package" },
      auth: { signIn: "Sign In", signUp: "Sign Up", email: "Email", password: "Password", confirmPassword: "Confirm Password", displayName: "Display Name", noAccount: "Don't have an account?", hasAccount: "Already have an account?", signingIn: "Signing in...", signingUp: "Signing up...", signInSuccess: "Signed in successfully!", signUpSuccess: "Account created! Check your email to verify.", signInError: "Sign in failed", signUpError: "Sign up failed", passwordMismatch: "Passwords do not match" },
      createShipment: { title: "Create Shipment", subtitle: "Ship your package with TransportHaven", senderInfo: "Sender Information", receiverInfo: "Receiver Information", packageDetails: "Package Details", name: "Full Name", street: "Street Address", city: "City", state: "State/Province", zip: "ZIP/Postal Code", country: "Country", weight: "Weight (kg)", length: "Length (cm)", width: "Width (cm)", height: "Height (cm)", serviceType: "Service Type", express: "Express Overnight", standard: "Standard Ground", economy: "Economy Saver", overnight: "Overnight Priority", signatureRequired: "Signature Required", submit: "Create Shipment", description: "Description" },
      international: { title: "International Shipping", subtitle: "Ship worldwide with confidence", heroDesc: "Customs clearance, duties calculation, and door-to-door tracking across 220+ countries.", countries: "Countries & Territories", customs: "Customs Clearance", doorToDoor: "Door-to-Door Tracking", getQuote: "Get International Quote", howItWorks: "How It Works", step1: "Prepare Documents", step1Desc: "Complete customs forms and commercial invoice.", step2: "Schedule Pickup", step2Desc: "We collect from your location at your preferred time.", step3: "Customs & Transit", step3Desc: "We handle all customs clearance and transit logistics.", step4: "Delivered", step4Desc: "Package delivered to destination with full tracking." },
      business: { title: "Business Solutions", subtitle: "Enterprise logistics tailored to your needs", heroDesc: "Volume discounts, dedicated account managers, API integration, and custom logistics solutions.", volumeShipping: "Volume Shipping", volumeDesc: "Save up to 40% with volume-based pricing tiers.", apiAccess: "API Integration", apiDesc: "RESTful APIs with webhook notifications for seamless integration.", dedicated: "Dedicated Support", dedicatedDesc: "24/7 dedicated account manager for enterprise clients.", analytics: "Advanced Analytics", analyticsDesc: "Real-time dashboards and custom reporting for your shipments.", getStarted: "Contact Sales", enterprise: "Enterprise", small: "Small Business", startup: "Startup" },
      about: { title: "About Us" }, careers: { title: "Careers" }, press: { title: "Press" }, sustainability: { title: "Sustainability" }, faq: { title: "FAQ" }, reviewsPage: { title: "Reviews" }, privacy: { title: "Privacy Policy" }, terms: { title: "Terms of Service" }, cookiesPage: { title: "Cookie Policy" }, servicesPage: { title: "Our Services" }, supportPage: { title: "Support" }, schedulePage: { title: "Schedule Pickup" }, quotePage: { title: "Get a Quote" }, servicesGuide: { title: "Services Guide" }, trackPage: { title: "Track Your Package" },
      darkMode: { light: "Light", dark: "Dark" }
    }
  },
  es: {
    translation: {
      nav: { home: "Inicio", track: "Rastrear", services: "Servicios", support: "Soporte", reviews: "Reseñas", getQuote: "COTIZAR", trackNow: "RASTREAR", signIn: "Iniciar Sesión", signUp: "Registrarse", signOut: "Cerrar Sesión", myAccount: "Mi Cuenta" },
      hero: {
        tag1: "RASTREO GPS EN TIEMPO REAL", tag2: "CARGA AÉREA", tag3: "COBERTURA NACIONAL",
        title1_1: "ENTREGAMOS", title1_2: "CERTEZA", title1_3: "NO SOLO PAQUETES",
        title2_1: "ENVÍO", title2_2: "NOCTURNO", title2_3: "EXPRESS",
        title3_1: "COSTA A", title3_2: "COSTA", title3_3: "EN DÍAS",
        desc1: "Rastreo GPS en vivo, actualizaciones instantáneas y visibilidad completa — desde la recogida hasta su puerta.",
        desc2: "Entrega al día siguiente garantizada antes de las 10:30 AM. Carga aérea prioritaria con rastreo en tiempo real.",
        desc3: "Nuestra flota de más de 500 vehículos entrega en los 50 estados con fiabilidad líder en la industria.",
        enterTracking: "Ingrese Número de Rastreo", trackBtn: "RASTREAR"
      },
      stats: { packages: "Paquetes Entregados", onTime: "Entrega a Tiempo", states: "Estados Cubiertos", liveTracking: "Rastreo en Vivo" },
      quickActions: { trackPackage: "Rastrear Paquete", realTimeUpdates: "Actualizaciones en tiempo real", getQuote: "Obtener Cotización", instantPricing: "Precios instantáneos", schedulePickup: "Programar Recogida", weComeToYou: "Vamos a usted", servicesGuide: "Guía de Servicios", compareOptions: "Comparar opciones" },
      services: { title: "Nuestros Servicios", subtitle: "SOLUCIONES DE ENVÍO", desc: "Desde express del mismo día hasta terrestre económico, tenemos la opción correcta para cada paquete.", expressTitle: "Express Nocturno", expressDesc: "Entrega al día siguiente garantizada antes de las 10:30 AM.", standardTitle: "Terrestre Estándar", standardDesc: "Entrega confiable en 3-5 días hábiles en todo EE.UU.", economyTitle: "Económico", economyDesc: "Opción económica con entrega en 5-7 días hábiles.", fastest: "MÁS RÁPIDO", popular: "POPULAR", value: "VALOR", learnMore: "Saber más" },
      freight: { title: "SERVICIOS DE CARGA", subtitle: "Soluciones Logísticas Globales", airTitle: "Carga Aérea", airDesc: "Carga aérea express mundial con manejo prioritario y despacho aduanero.", seaTitle: "Carga Marítima", seaDesc: "Flete marítimo rentable para envíos grandes con rastreo completo.", landTitle: "Carga Terrestre", landDesc: "Transporte terrestre confiable con cobertura nacional y rastreo GPS.", getStarted: "Comenzar" },
      features: { realTimeTitle: "RASTREO GPS EN VIVO EN CADA PAQUETE", realTimeDesc: "Observe su paquete moverse en tiempo real en un mapa interactivo.", seeTracking: "VER RASTREO EN VIVO", facilityTitle: "INSTALACIONES DE CLASIFICACIÓN DE ÚLTIMA GENERACIÓN", facilityDesc: "Nuestra red de centros automatizados procesa miles de paquetes por hora.", podTitle: "PRUEBA DE ENTREGA CADA VEZ", podDesc: "Nuestros conductores capturan prueba fotográfica en cada entrega." },
      testimonials: { title: "CONFIADO POR MILES", seeAll: "VER TODAS LAS RESEÑAS" },
      cta: { title: "¿LISTO PARA ENVIAR?", desc: "Comience a rastrear sus paquetes hoy con la plataforma logística líder de TransportHaven.", trackPackage: "RASTREAR PAQUETE", getQuote: "OBTENER COTIZACIÓN" },
      footer: { tagline: "Entregamos certeza, no solo paquetes.", ship: "Enviar", company: "Empresa", support: "Soporte", trackPackage: "Rastrear Paquete", getQuote: "Obtener Cotización", schedulePickup: "Programar Recogida", serviceGuide: "Guía de Servicios", aboutUs: "Sobre Nosotros", careers: "Carreras", press: "Prensa", sustainability: "Sostenibilidad", faq: "Preguntas Frecuentes", reviews: "Reseñas", privacy: "Política de Privacidad", terms: "Términos de Servicio", cookies: "Política de Cookies", rights: "Todos los derechos reservados." },
      topBar: { trackPackage: "Rastrear un Paquete" },
      auth: { signIn: "Iniciar Sesión", signUp: "Registrarse", email: "Correo Electrónico", password: "Contraseña", confirmPassword: "Confirmar Contraseña", displayName: "Nombre", noAccount: "¿No tiene cuenta?", hasAccount: "¿Ya tiene cuenta?", signingIn: "Iniciando sesión...", signingUp: "Registrando...", signInSuccess: "¡Sesión iniciada!", signUpSuccess: "¡Cuenta creada! Verifique su correo.", signInError: "Error al iniciar sesión", signUpError: "Error al registrarse", passwordMismatch: "Las contraseñas no coinciden" },
      createShipment: { title: "Crear Envío", subtitle: "Envíe su paquete con TransportHaven", senderInfo: "Información del Remitente", receiverInfo: "Información del Destinatario", packageDetails: "Detalles del Paquete", name: "Nombre Completo", street: "Dirección", city: "Ciudad", state: "Estado/Provincia", zip: "Código Postal", country: "País", weight: "Peso (kg)", length: "Largo (cm)", width: "Ancho (cm)", height: "Alto (cm)", serviceType: "Tipo de Servicio", express: "Express Nocturno", standard: "Terrestre Estándar", economy: "Económico", overnight: "Prioridad Nocturna", signatureRequired: "Firma Requerida", submit: "Crear Envío", description: "Descripción" },
      international: { title: "Envío Internacional", subtitle: "Envíe a todo el mundo con confianza", heroDesc: "Despacho aduanero, cálculo de aranceles y rastreo puerta a puerta en más de 220 países.", countries: "Países y Territorios", customs: "Despacho Aduanero", doorToDoor: "Rastreo Puerta a Puerta", getQuote: "Cotización Internacional", howItWorks: "Cómo Funciona", step1: "Preparar Documentos", step1Desc: "Complete formularios aduaneros y factura comercial.", step2: "Programar Recogida", step2Desc: "Recogemos en su ubicación a la hora preferida.", step3: "Aduanas y Tránsito", step3Desc: "Gestionamos todo el despacho aduanero y logística.", step4: "Entregado", step4Desc: "Paquete entregado con rastreo completo." },
      business: { title: "Soluciones Empresariales", subtitle: "Logística empresarial a su medida", heroDesc: "Descuentos por volumen, gestores dedicados, integración API y soluciones logísticas personalizadas.", volumeShipping: "Envío por Volumen", volumeDesc: "Ahorre hasta 40% con precios por volumen.", apiAccess: "Integración API", apiDesc: "APIs RESTful con notificaciones webhook.", dedicated: "Soporte Dedicado", dedicatedDesc: "Gestor de cuenta dedicado 24/7.", analytics: "Analítica Avanzada", analyticsDesc: "Dashboards en tiempo real e informes personalizados.", getStarted: "Contactar Ventas", enterprise: "Empresa", small: "Pequeña Empresa", startup: "Startup" },
      about: { title: "Sobre Nosotros" }, careers: { title: "Carreras" }, press: { title: "Prensa" }, sustainability: { title: "Sostenibilidad" }, faq: { title: "Preguntas Frecuentes" }, reviewsPage: { title: "Reseñas" }, privacy: { title: "Política de Privacidad" }, terms: { title: "Términos de Servicio" }, cookiesPage: { title: "Política de Cookies" }, servicesPage: { title: "Nuestros Servicios" }, supportPage: { title: "Soporte" }, schedulePage: { title: "Programar Recogida" }, quotePage: { title: "Obtener Cotización" }, servicesGuide: { title: "Guía de Servicios" }, trackPage: { title: "Rastrear su Paquete" },
      darkMode: { light: "Claro", dark: "Oscuro" }
    }
  },
  fr: {
    translation: {
      nav: { home: "Accueil", track: "Suivi", services: "Services", support: "Support", reviews: "Avis", getQuote: "DEVIS", trackNow: "SUIVRE", signIn: "Connexion", signUp: "Inscription", signOut: "Déconnexion", myAccount: "Mon Compte" },
      hero: {
        tag1: "SUIVI GPS EN TEMPS RÉEL", tag2: "FRET AÉRIEN", tag3: "COUVERTURE NATIONALE",
        title1_1: "LIVRER LA", title1_2: "CERTITUDE", title1_3: "PAS QUE DES COLIS",
        title2_1: "LIVRAISON", title2_2: "EXPRESS", title2_3: "DE NUIT",
        title3_1: "D'UN BOUT", title3_2: "À L'AUTRE", title3_3: "EN JOURS",
        desc1: "Suivi GPS en direct, mises à jour instantanées et visibilité complète — de la collecte à votre porte.",
        desc2: "Livraison le lendemain garantie avant 10h30. Fret aérien prioritaire avec suivi en temps réel.",
        desc3: "Notre flotte de plus de 500 véhicules livre dans les 50 états avec une fiabilité de premier plan.",
        enterTracking: "Entrez le Numéro de Suivi", trackBtn: "SUIVRE"
      },
      stats: { packages: "Colis Livrés", onTime: "Livraison à Temps", states: "États Couverts", liveTracking: "Suivi en Direct" },
      quickActions: { trackPackage: "Suivre un Colis", realTimeUpdates: "Mises à jour en temps réel", getQuote: "Obtenir un Devis", instantPricing: "Tarifs instantanés", schedulePickup: "Planifier un Enlèvement", weComeToYou: "Nous venons à vous", servicesGuide: "Guide des Services", compareOptions: "Comparer les options" },
      services: { title: "Nos Services", subtitle: "SOLUTIONS D'EXPÉDITION", desc: "De l'express même jour au terrestre économique, nous avons la bonne option pour chaque colis.", expressTitle: "Express de Nuit", expressDesc: "Livraison le lendemain garantie avant 10h30.", standardTitle: "Terrestre Standard", standardDesc: "Livraison fiable en 3-5 jours ouvrables.", economyTitle: "Économique", economyDesc: "Option économique avec livraison en 5-7 jours ouvrables.", fastest: "LE PLUS RAPIDE", popular: "POPULAIRE", value: "VALEUR", learnMore: "En savoir plus" },
      freight: { title: "SERVICES DE FRET", subtitle: "Solutions Logistiques Mondiales", airTitle: "Fret Aérien", airDesc: "Cargo aérien express mondial avec manutention prioritaire.", seaTitle: "Fret Maritime", seaDesc: "Fret maritime rentable pour les grands envois.", landTitle: "Fret Terrestre", landDesc: "Transport terrestre fiable avec couverture nationale.", getStarted: "Commencer" },
      features: { realTimeTitle: "SUIVI GPS EN DIRECT SUR CHAQUE COLIS", realTimeDesc: "Regardez votre colis se déplacer en temps réel sur une carte interactive.", seeTracking: "VOIR LE SUIVI EN DIRECT", facilityTitle: "CENTRES DE TRI DE POINTE", facilityDesc: "Notre réseau de centres automatisés traite des milliers de colis par heure.", podTitle: "PREUVE DE LIVRAISON À CHAQUE FOIS", podDesc: "Nos chauffeurs capturent une preuve photo à chaque livraison." },
      testimonials: { title: "APPROUVÉ PAR DES MILLIERS", seeAll: "VOIR TOUS LES AVIS" },
      cta: { title: "PRÊT À EXPÉDIER?", desc: "Commencez à suivre vos colis aujourd'hui avec la plateforme logistique leader de TransportHaven.", trackPackage: "SUIVRE UN COLIS", getQuote: "OBTENIR UN DEVIS" },
      footer: { tagline: "Livrer la certitude, pas seulement des colis.", ship: "Expédier", company: "Entreprise", support: "Support", trackPackage: "Suivre un Colis", getQuote: "Obtenir un Devis", schedulePickup: "Planifier Enlèvement", serviceGuide: "Guide Services", aboutUs: "À Propos", careers: "Carrières", press: "Presse", sustainability: "Durabilité", faq: "FAQ", reviews: "Avis", privacy: "Politique de Confidentialité", terms: "Conditions d'Utilisation", cookies: "Politique de Cookies", rights: "Tous droits réservés." },
      topBar: { trackPackage: "Suivre un Colis" },
      auth: { signIn: "Connexion", signUp: "Inscription", email: "E-mail", password: "Mot de passe", confirmPassword: "Confirmer le mot de passe", displayName: "Nom d'affichage", noAccount: "Pas de compte?", hasAccount: "Déjà un compte?", signingIn: "Connexion en cours...", signingUp: "Inscription en cours...", signInSuccess: "Connecté avec succès!", signUpSuccess: "Compte créé! Vérifiez votre e-mail.", signInError: "Échec de la connexion", signUpError: "Échec de l'inscription", passwordMismatch: "Les mots de passe ne correspondent pas" },
      createShipment: { title: "Créer un Envoi", subtitle: "Expédiez votre colis avec TransportHaven", senderInfo: "Informations Expéditeur", receiverInfo: "Informations Destinataire", packageDetails: "Détails du Colis", name: "Nom Complet", street: "Adresse", city: "Ville", state: "État/Province", zip: "Code Postal", country: "Pays", weight: "Poids (kg)", length: "Longueur (cm)", width: "Largeur (cm)", height: "Hauteur (cm)", serviceType: "Type de Service", express: "Express de Nuit", standard: "Terrestre Standard", economy: "Économique", overnight: "Priorité de Nuit", signatureRequired: "Signature Requise", submit: "Créer l'Envoi", description: "Description" },
      international: { title: "Expédition Internationale", subtitle: "Expédiez dans le monde entier en toute confiance", heroDesc: "Dédouanement, calcul des droits et suivi porte à porte dans plus de 220 pays.", countries: "Pays et Territoires", customs: "Dédouanement", doorToDoor: "Suivi Porte à Porte", getQuote: "Devis International", howItWorks: "Comment ça Marche", step1: "Préparer les Documents", step1Desc: "Remplissez les formulaires douaniers et la facture commerciale.", step2: "Planifier l'Enlèvement", step2Desc: "Nous collectons à votre adresse à l'heure souhaitée.", step3: "Douanes et Transit", step3Desc: "Nous gérons tout le dédouanement et la logistique.", step4: "Livré", step4Desc: "Colis livré avec suivi complet." },
      business: { title: "Solutions Entreprise", subtitle: "Logistique entreprise sur mesure", heroDesc: "Remises sur volume, gestionnaires dédiés, intégration API et solutions logistiques personnalisées.", volumeShipping: "Expédition en Volume", volumeDesc: "Économisez jusqu'à 40% avec nos tarifs par volume.", apiAccess: "Intégration API", apiDesc: "APIs RESTful avec notifications webhook.", dedicated: "Support Dédié", dedicatedDesc: "Gestionnaire de compte dédié 24/7.", analytics: "Analytique Avancée", analyticsDesc: "Tableaux de bord en temps réel et rapports personnalisés.", getStarted: "Contacter les Ventes", enterprise: "Entreprise", small: "Petite Entreprise", startup: "Startup" },
      about: { title: "À Propos" }, careers: { title: "Carrières" }, press: { title: "Presse" }, sustainability: { title: "Durabilité" }, faq: { title: "FAQ" }, reviewsPage: { title: "Avis" }, privacy: { title: "Politique de Confidentialité" }, terms: { title: "Conditions d'Utilisation" }, cookiesPage: { title: "Politique de Cookies" }, servicesPage: { title: "Nos Services" }, supportPage: { title: "Support" }, schedulePage: { title: "Planifier un Enlèvement" }, quotePage: { title: "Obtenir un Devis" }, servicesGuide: { title: "Guide des Services" }, trackPage: { title: "Suivre votre Colis" },
      darkMode: { light: "Clair", dark: "Sombre" }
    }
  },
  it: {
    translation: {
      nav: { home: "Home", track: "Traccia", services: "Servizi", support: "Supporto", reviews: "Recensioni", getQuote: "PREVENTIVO", trackNow: "TRACCIA", signIn: "Accedi", signUp: "Registrati", signOut: "Esci", myAccount: "Il Mio Account" },
      hero: {
        tag1: "TRACCIAMENTO GPS IN TEMPO REALE", tag2: "TRASPORTO AEREO", tag3: "COPERTURA NAZIONALE",
        title1_1: "CONSEGNIAMO", title1_2: "CERTEZZA", title1_3: "NON SOLO PACCHI",
        title2_1: "CONSEGNA", title2_2: "EXPRESS", title2_3: "NOTTURNA",
        title3_1: "DA COSTA", title3_2: "A COSTA", title3_3: "IN GIORNI",
        desc1: "Tracciamento GPS in tempo reale, aggiornamenti istantanei e visibilità completa — dal ritiro alla consegna.",
        desc2: "Consegna il giorno successivo garantita entro le 10:30. Trasporto aereo prioritario con tracciamento in tempo reale.",
        desc3: "La nostra flotta di oltre 500 veicoli consegna in tutti i 50 stati con affidabilità leader del settore.",
        enterTracking: "Inserisci Numero di Tracciamento", trackBtn: "TRACCIA"
      },
      stats: { packages: "Pacchi Consegnati", onTime: "Consegna Puntuale", states: "Stati Coperti", liveTracking: "Tracciamento Live" },
      quickActions: { trackPackage: "Traccia un Pacco", realTimeUpdates: "Aggiornamenti in tempo reale", getQuote: "Richiedi Preventivo", instantPricing: "Prezzi istantanei", schedulePickup: "Programma Ritiro", weComeToYou: "Veniamo da te", servicesGuide: "Guida Servizi", compareOptions: "Confronta opzioni" },
      services: { title: "I Nostri Servizi", subtitle: "SOLUZIONI DI SPEDIZIONE", desc: "Dall'express dello stesso giorno al terrestre economico, abbiamo l'opzione giusta per ogni pacco.", expressTitle: "Express Notturno", expressDesc: "Consegna il giorno successivo garantita entro le 10:30.", standardTitle: "Terrestre Standard", standardDesc: "Consegna affidabile in 3-5 giorni lavorativi.", economyTitle: "Economico", economyDesc: "Opzione economica con consegna in 5-7 giorni lavorativi.", fastest: "PIÙ VELOCE", popular: "POPOLARE", value: "VALORE", learnMore: "Scopri di più" },
      freight: { title: "SERVIZI DI TRASPORTO", subtitle: "Soluzioni Logistiche Globali", airTitle: "Trasporto Aereo", airDesc: "Cargo aereo express mondiale con gestione prioritaria.", seaTitle: "Trasporto Marittimo", seaDesc: "Trasporto marittimo conveniente per grandi spedizioni.", landTitle: "Trasporto Terrestre", landDesc: "Trasporto terrestre affidabile con copertura nazionale.", getStarted: "Inizia" },
      features: { realTimeTitle: "TRACCIAMENTO GPS LIVE SU OGNI PACCO", realTimeDesc: "Guarda il tuo pacco muoversi in tempo reale su una mappa interattiva.", seeTracking: "VEDI TRACCIAMENTO LIVE", facilityTitle: "CENTRI DI SMISTAMENTO ALL'AVANGUARDIA", facilityDesc: "La nostra rete di centri automatizzati elabora migliaia di pacchi all'ora.", podTitle: "PROVA DI CONSEGNA OGNI VOLTA", podDesc: "I nostri autisti catturano prove fotografiche ad ogni consegna." },
      testimonials: { title: "FIDATO DA MIGLIAIA", seeAll: "VEDI TUTTE LE RECENSIONI" },
      cta: { title: "PRONTO A SPEDIRE?", desc: "Inizia a tracciare i tuoi pacchi oggi con la piattaforma logistica leader di TransportHaven.", trackPackage: "TRACCIA UN PACCO", getQuote: "RICHIEDI PREVENTIVO" },
      footer: { tagline: "Consegniamo certezza, non solo pacchi.", ship: "Spedisci", company: "Azienda", support: "Supporto", trackPackage: "Traccia Pacco", getQuote: "Preventivo", schedulePickup: "Programma Ritiro", serviceGuide: "Guida Servizi", aboutUs: "Chi Siamo", careers: "Carriere", press: "Stampa", sustainability: "Sostenibilità", faq: "FAQ", reviews: "Recensioni", privacy: "Privacy", terms: "Termini di Servizio", cookies: "Cookie", rights: "Tutti i diritti riservati." },
      topBar: { trackPackage: "Traccia un Pacco" },
      auth: { signIn: "Accedi", signUp: "Registrati", email: "E-mail", password: "Password", confirmPassword: "Conferma Password", displayName: "Nome Visualizzato", noAccount: "Non hai un account?", hasAccount: "Hai già un account?", signingIn: "Accesso in corso...", signingUp: "Registrazione in corso...", signInSuccess: "Accesso effettuato!", signUpSuccess: "Account creato! Verifica la tua email.", signInError: "Accesso fallito", signUpError: "Registrazione fallita", passwordMismatch: "Le password non corrispondono" },
      createShipment: { title: "Crea Spedizione", subtitle: "Spedisci il tuo pacco con TransportHaven", senderInfo: "Info Mittente", receiverInfo: "Info Destinatario", packageDetails: "Dettagli Pacco", name: "Nome Completo", street: "Indirizzo", city: "Città", state: "Stato/Provincia", zip: "CAP", country: "Paese", weight: "Peso (kg)", length: "Lunghezza (cm)", width: "Larghezza (cm)", height: "Altezza (cm)", serviceType: "Tipo Servizio", express: "Express Notturno", standard: "Terrestre Standard", economy: "Economico", overnight: "Priorità Notturna", signatureRequired: "Firma Richiesta", submit: "Crea Spedizione", description: "Descrizione" },
      international: { title: "Spedizione Internazionale", subtitle: "Spedisci in tutto il mondo con fiducia", heroDesc: "Sdoganamento, calcolo dazi e tracciamento porta a porta in oltre 220 paesi.", countries: "Paesi e Territori", customs: "Sdoganamento", doorToDoor: "Tracciamento Porta a Porta", getQuote: "Preventivo Internazionale", howItWorks: "Come Funziona", step1: "Prepara Documenti", step1Desc: "Compila moduli doganali e fattura commerciale.", step2: "Programma Ritiro", step2Desc: "Ritiriamo al tuo indirizzo all'ora preferita.", step3: "Dogana e Transito", step3Desc: "Gestiamo tutto lo sdoganamento e la logistica.", step4: "Consegnato", step4Desc: "Pacco consegnato con tracciamento completo." },
      business: { title: "Soluzioni Business", subtitle: "Logistica aziendale su misura", heroDesc: "Sconti volume, account manager dedicati, integrazione API e soluzioni logistiche personalizzate.", volumeShipping: "Spedizione a Volume", volumeDesc: "Risparmia fino al 40% con prezzi a volume.", apiAccess: "Integrazione API", apiDesc: "API RESTful con notifiche webhook.", dedicated: "Supporto Dedicato", dedicatedDesc: "Account manager dedicato 24/7.", analytics: "Analisi Avanzata", analyticsDesc: "Dashboard in tempo reale e report personalizzati.", getStarted: "Contatta Vendite", enterprise: "Enterprise", small: "Piccola Impresa", startup: "Startup" },
      about: { title: "Chi Siamo" }, careers: { title: "Carriere" }, press: { title: "Stampa" }, sustainability: { title: "Sostenibilità" }, faq: { title: "FAQ" }, reviewsPage: { title: "Recensioni" }, privacy: { title: "Privacy" }, terms: { title: "Termini di Servizio" }, cookiesPage: { title: "Cookie" }, servicesPage: { title: "I Nostri Servizi" }, supportPage: { title: "Supporto" }, schedulePage: { title: "Programma Ritiro" }, quotePage: { title: "Preventivo" }, servicesGuide: { title: "Guida Servizi" }, trackPage: { title: "Traccia il Tuo Pacco" },
      darkMode: { light: "Chiaro", dark: "Scuro" }
    }
  },
  de: {
    translation: {
      nav: { home: "Startseite", track: "Verfolgen", services: "Dienste", support: "Support", reviews: "Bewertungen", getQuote: "ANGEBOT", trackNow: "VERFOLGEN", signIn: "Anmelden", signUp: "Registrieren", signOut: "Abmelden", myAccount: "Mein Konto" },
      hero: {
        tag1: "GPS-VERFOLGUNG IN ECHTZEIT", tag2: "LUFTFRACHT", tag3: "LANDESWEITE ABDECKUNG",
        title1_1: "WIR LIEFERN", title1_2: "SICHERHEIT", title1_3: "NICHT NUR PAKETE",
        title2_1: "EXPRESS", title2_2: "ÜBER NACHT", title2_3: "LIEFERUNG",
        title3_1: "KÜSTE ZU", title3_2: "KÜSTE", title3_3: "IN TAGEN",
        desc1: "Live GPS-Verfolgung, sofortige Statusupdates und vollständige Liefertransparenz — von der Abholung bis an Ihre Tür.",
        desc2: "Lieferung am nächsten Tag garantiert bis 10:30 Uhr. Prioritäts-Luftfracht mit Echtzeit-Verfolgung.",
        desc3: "Unsere Flotte von über 500 Fahrzeugen liefert in alle 50 Staaten mit branchenführender Zuverlässigkeit.",
        enterTracking: "Sendungsnummer Eingeben", trackBtn: "VERFOLGEN"
      },
      stats: { packages: "Pakete Zugestellt", onTime: "Pünktliche Zustellung", states: "Abgedeckte Staaten", liveTracking: "Live-Verfolgung" },
      quickActions: { trackPackage: "Paket Verfolgen", realTimeUpdates: "Echtzeit-Updates", getQuote: "Angebot Einholen", instantPricing: "Sofortige Preise", schedulePickup: "Abholung Planen", weComeToYou: "Wir kommen zu Ihnen", servicesGuide: "Serviceguide", compareOptions: "Optionen vergleichen" },
      services: { title: "Unsere Dienste", subtitle: "VERSANDLÖSUNGEN", desc: "Von Express am selben Tag bis zum wirtschaftlichen Landweg – die richtige Lieferoption für jedes Paket.", expressTitle: "Express Über Nacht", expressDesc: "Zustellung am nächsten Tag garantiert bis 10:30 Uhr.", standardTitle: "Standard Landweg", standardDesc: "Zuverlässige Zustellung in 3-5 Werktagen.", economyTitle: "Economy", economyDesc: "Günstige Option mit 5-7 Werktagen Lieferzeit.", fastest: "SCHNELLSTE", popular: "BELIEBT", value: "WERT", learnMore: "Mehr erfahren" },
      freight: { title: "FRACHTDIENSTE", subtitle: "Globale Logistiklösungen", airTitle: "Luftfracht", airDesc: "Express-Luftfracht weltweit mit Prioritätsbehandlung.", seaTitle: "Seefracht", seaDesc: "Kostengünstige Seefracht für große Sendungen.", landTitle: "Landfracht", landDesc: "Zuverlässiger Landtransport mit landesweiter Abdeckung.", getStarted: "Starten" },
      features: { realTimeTitle: "LIVE GPS-VERFOLGUNG AUF JEDEM PAKET", realTimeDesc: "Beobachten Sie Ihr Paket in Echtzeit auf einer interaktiven Karte.", seeTracking: "LIVE-VERFOLGUNG SEHEN", facilityTitle: "MODERNSTE SORTIERANLAGEN", facilityDesc: "Unser Netzwerk automatisierter Zentren verarbeitet tausende Pakete pro Stunde.", podTitle: "ZUSTELLNACHWEIS JEDES MAL", podDesc: "Unsere Fahrer erfassen bei jeder Zustellung einen Fotonachweis." },
      testimonials: { title: "VERTRAUT VON TAUSENDEN", seeAll: "ALLE BEWERTUNGEN SEHEN" },
      cta: { title: "BEREIT ZUM VERSENDEN?", desc: "Beginnen Sie noch heute mit der Verfolgung Ihrer Pakete mit TransportHavens führender Logistikplattform.", trackPackage: "PAKET VERFOLGEN", getQuote: "ANGEBOT EINHOLEN" },
      footer: { tagline: "Wir liefern Sicherheit, nicht nur Pakete.", ship: "Versenden", company: "Unternehmen", support: "Support", trackPackage: "Paket Verfolgen", getQuote: "Angebot Einholen", schedulePickup: "Abholung Planen", serviceGuide: "Serviceguide", aboutUs: "Über Uns", careers: "Karriere", press: "Presse", sustainability: "Nachhaltigkeit", faq: "FAQ", reviews: "Bewertungen", privacy: "Datenschutz", terms: "Nutzungsbedingungen", cookies: "Cookie-Richtlinie", rights: "Alle Rechte vorbehalten." },
      topBar: { trackPackage: "Paket Verfolgen" },
      auth: { signIn: "Anmelden", signUp: "Registrieren", email: "E-Mail", password: "Passwort", confirmPassword: "Passwort Bestätigen", displayName: "Anzeigename", noAccount: "Kein Konto?", hasAccount: "Bereits ein Konto?", signingIn: "Anmeldung...", signingUp: "Registrierung...", signInSuccess: "Erfolgreich angemeldet!", signUpSuccess: "Konto erstellt! Überprüfen Sie Ihre E-Mail.", signInError: "Anmeldung fehlgeschlagen", signUpError: "Registrierung fehlgeschlagen", passwordMismatch: "Passwörter stimmen nicht überein" },
      createShipment: { title: "Sendung Erstellen", subtitle: "Versenden Sie Ihr Paket mit TransportHaven", senderInfo: "Absenderinformationen", receiverInfo: "Empfängerinformationen", packageDetails: "Paketdetails", name: "Vollständiger Name", street: "Straße", city: "Stadt", state: "Bundesland", zip: "PLZ", country: "Land", weight: "Gewicht (kg)", length: "Länge (cm)", width: "Breite (cm)", height: "Höhe (cm)", serviceType: "Serviceart", express: "Express Über Nacht", standard: "Standard Landweg", economy: "Economy", overnight: "Nacht-Priorität", signatureRequired: "Unterschrift Erforderlich", submit: "Sendung Erstellen", description: "Beschreibung" },
      international: { title: "Internationaler Versand", subtitle: "Weltweit versenden mit Vertrauen", heroDesc: "Zollabfertigung, Zollberechnung und Tür-zu-Tür-Verfolgung in über 220 Ländern.", countries: "Länder und Gebiete", customs: "Zollabfertigung", doorToDoor: "Tür-zu-Tür-Verfolgung", getQuote: "Internationales Angebot", howItWorks: "So Funktioniert's", step1: "Dokumente Vorbereiten", step1Desc: "Füllen Sie Zollformulare und Handelsrechnung aus.", step2: "Abholung Planen", step2Desc: "Wir holen an Ihrem Standort zur gewünschten Zeit ab.", step3: "Zoll und Transit", step3Desc: "Wir übernehmen die gesamte Zollabfertigung und Logistik.", step4: "Zugestellt", step4Desc: "Paket mit vollständiger Verfolgung zugestellt." },
      business: { title: "Geschäftslösungen", subtitle: "Unternehmenslogistik nach Maß", heroDesc: "Mengenrabatte, dedizierte Betreuer, API-Integration und maßgeschneiderte Logistiklösungen.", volumeShipping: "Mengenversand", volumeDesc: "Sparen Sie bis zu 40% mit mengenbasierten Preisen.", apiAccess: "API-Integration", apiDesc: "RESTful APIs mit Webhook-Benachrichtigungen.", dedicated: "Dedizierter Support", dedicatedDesc: "24/7 dedizierter Account Manager.", analytics: "Erweiterte Analytik", analyticsDesc: "Echtzeit-Dashboards und benutzerdefinierte Berichte.", getStarted: "Vertrieb Kontaktieren", enterprise: "Unternehmen", small: "Kleinunternehmen", startup: "Startup" },
      about: { title: "Über Uns" }, careers: { title: "Karriere" }, press: { title: "Presse" }, sustainability: { title: "Nachhaltigkeit" }, faq: { title: "FAQ" }, reviewsPage: { title: "Bewertungen" }, privacy: { title: "Datenschutz" }, terms: { title: "Nutzungsbedingungen" }, cookiesPage: { title: "Cookie-Richtlinie" }, servicesPage: { title: "Unsere Dienste" }, supportPage: { title: "Support" }, schedulePage: { title: "Abholung Planen" }, quotePage: { title: "Angebot Einholen" }, servicesGuide: { title: "Serviceguide" }, trackPage: { title: "Ihr Paket Verfolgen" },
      darkMode: { light: "Hell", dark: "Dunkel" }
    }
  },
  ar: {
    translation: {
      nav: { home: "الرئيسية", track: "تتبع", services: "الخدمات", support: "الدعم", reviews: "التقييمات", getQuote: "طلب عرض", trackNow: "تتبع الآن", signIn: "تسجيل الدخول", signUp: "إنشاء حساب", signOut: "تسجيل الخروج", myAccount: "حسابي" },
      hero: {
        tag1: "تتبع GPS في الوقت الفعلي", tag2: "الشحن الجوي", tag3: "تغطية وطنية",
        title1_1: "نوصل", title1_2: "اليقين", title1_3: "ليس فقط الطرود",
        title2_1: "توصيل", title2_2: "سريع", title2_3: "ليلي",
        title3_1: "من ساحل", title3_2: "إلى ساحل", title3_3: "في أيام",
        desc1: "تتبع GPS مباشر، تحديثات فورية وشفافية كاملة — من الاستلام حتى بابك.",
        desc2: "توصيل في اليوم التالي مضمون قبل 10:30 صباحاً. شحن جوي ذو أولوية مع تتبع في الوقت الفعلي.",
        desc3: "أسطولنا المكون من أكثر من 500 مركبة يوصل إلى جميع الولايات الـ 50.",
        enterTracking: "أدخل رقم التتبع", trackBtn: "تتبع"
      },
      stats: { packages: "طرود تم توصيلها", onTime: "توصيل في الوقت", states: "ولاية مغطاة", liveTracking: "تتبع مباشر" },
      quickActions: { trackPackage: "تتبع طرد", realTimeUpdates: "تحديثات فورية", getQuote: "طلب عرض سعر", instantPricing: "أسعار فورية", schedulePickup: "جدولة الاستلام", weComeToYou: "نأتي إليك", servicesGuide: "دليل الخدمات", compareOptions: "مقارنة الخيارات" },
      services: { title: "خدماتنا", subtitle: "حلول الشحن", desc: "من الشحن السريع إلى الاقتصادي، لدينا الخيار المناسب لكل طرد.", expressTitle: "سريع ليلي", expressDesc: "توصيل في اليوم التالي مضمون.", standardTitle: "بري عادي", standardDesc: "توصيل موثوق في 3-5 أيام عمل.", economyTitle: "اقتصادي", economyDesc: "خيار اقتصادي مع توصيل في 5-7 أيام عمل.", fastest: "الأسرع", popular: "شائع", value: "قيمة", learnMore: "اعرف المزيد" },
      freight: { title: "خدمات الشحن", subtitle: "حلول لوجستية عالمية", airTitle: "الشحن الجوي", airDesc: "شحن جوي سريع عالمي مع معالجة ذات أولوية.", seaTitle: "الشحن البحري", seaDesc: "شحن بحري فعال من حيث التكلفة.", landTitle: "الشحن البري", landDesc: "نقل بري موثوق مع تغطية وطنية.", getStarted: "ابدأ" },
      features: { realTimeTitle: "تتبع GPS مباشر على كل طرد", realTimeDesc: "شاهد طردك يتحرك في الوقت الفعلي على خريطة تفاعلية.", seeTracking: "شاهد التتبع المباشر", facilityTitle: "مرافق فرز متطورة", facilityDesc: "شبكتنا من المراكز الآلية تعالج آلاف الطرود في الساعة.", podTitle: "إثبات التوصيل في كل مرة", podDesc: "يلتقط سائقونا دليلاً مصوراً عند كل توصيل." },
      testimonials: { title: "موثوق من الآلاف", seeAll: "عرض جميع التقييمات" },
      cta: { title: "مستعد للشحن؟", desc: "ابدأ في تتبع طرودك اليوم مع منصة TransportHaven اللوجستية.", trackPackage: "تتبع طرد", getQuote: "طلب عرض سعر" },
      footer: { tagline: "نوصل اليقين، ليس فقط الطرود.", ship: "شحن", company: "الشركة", support: "الدعم", trackPackage: "تتبع طرد", getQuote: "طلب عرض", schedulePickup: "جدولة استلام", serviceGuide: "دليل الخدمات", aboutUs: "عن الشركة", careers: "وظائف", press: "الصحافة", sustainability: "الاستدامة", faq: "الأسئلة الشائعة", reviews: "التقييمات", privacy: "سياسة الخصوصية", terms: "شروط الخدمة", cookies: "سياسة ملفات تعريف الارتباط", rights: "جميع الحقوق محفوظة." },
      topBar: { trackPackage: "تتبع طرد" },
      auth: { signIn: "تسجيل الدخول", signUp: "إنشاء حساب", email: "البريد الإلكتروني", password: "كلمة المرور", confirmPassword: "تأكيد كلمة المرور", displayName: "الاسم", noAccount: "ليس لديك حساب؟", hasAccount: "لديك حساب بالفعل؟", signingIn: "جاري تسجيل الدخول...", signingUp: "جاري إنشاء الحساب...", signInSuccess: "تم تسجيل الدخول!", signUpSuccess: "تم إنشاء الحساب! تحقق من بريدك.", signInError: "فشل تسجيل الدخول", signUpError: "فشل إنشاء الحساب", passwordMismatch: "كلمات المرور غير متطابقة" },
      createShipment: { title: "إنشاء شحنة", subtitle: "أرسل طردك مع TransportHaven", senderInfo: "معلومات المرسل", receiverInfo: "معلومات المستلم", packageDetails: "تفاصيل الطرد", name: "الاسم الكامل", street: "العنوان", city: "المدينة", state: "الولاية/المقاطعة", zip: "الرمز البريدي", country: "البلد", weight: "الوزن (كغ)", length: "الطول (سم)", width: "العرض (سم)", height: "الارتفاع (سم)", serviceType: "نوع الخدمة", express: "سريع ليلي", standard: "بري عادي", economy: "اقتصادي", overnight: "أولوية ليلية", signatureRequired: "توقيع مطلوب", submit: "إنشاء شحنة", description: "الوصف" },
      international: { title: "الشحن الدولي", subtitle: "أرسل حول العالم بثقة", heroDesc: "تخليص جمركي وتتبع من الباب إلى الباب في أكثر من 220 دولة.", countries: "دول ومناطق", customs: "تخليص جمركي", doorToDoor: "تتبع من الباب للباب", getQuote: "عرض سعر دولي", howItWorks: "كيف يعمل", step1: "تحضير المستندات", step1Desc: "أكمل النماذج الجمركية والفاتورة التجارية.", step2: "جدولة الاستلام", step2Desc: "نستلم من موقعك في الوقت المفضل.", step3: "الجمارك والعبور", step3Desc: "نتولى جميع إجراءات التخليص الجمركي.", step4: "تم التوصيل", step4Desc: "طرد تم توصيله مع تتبع كامل." },
      business: { title: "حلول الأعمال", subtitle: "لوجستيات مؤسسية مصممة خصيصاً", heroDesc: "خصومات على الكميات، مديرين مخصصين، تكامل API وحلول لوجستية مخصصة.", volumeShipping: "شحن بالكمية", volumeDesc: "وفر حتى 40% مع أسعار الكميات.", apiAccess: "تكامل API", apiDesc: "واجهات برمجة RESTful مع إشعارات webhook.", dedicated: "دعم مخصص", dedicatedDesc: "مدير حساب مخصص 24/7.", analytics: "تحليلات متقدمة", analyticsDesc: "لوحات معلومات فورية وتقارير مخصصة.", getStarted: "تواصل مع المبيعات", enterprise: "مؤسسة", small: "شركة صغيرة", startup: "شركة ناشئة" },
      about: { title: "عن الشركة" }, careers: { title: "وظائف" }, press: { title: "الصحافة" }, sustainability: { title: "الاستدامة" }, faq: { title: "الأسئلة الشائعة" }, reviewsPage: { title: "التقييمات" }, privacy: { title: "سياسة الخصوصية" }, terms: { title: "شروط الخدمة" }, cookiesPage: { title: "سياسة ملفات تعريف الارتباط" }, servicesPage: { title: "خدماتنا" }, supportPage: { title: "الدعم" }, schedulePage: { title: "جدولة الاستلام" }, quotePage: { title: "طلب عرض سعر" }, servicesGuide: { title: "دليل الخدمات" }, trackPage: { title: "تتبع طردك" },
      darkMode: { light: "فاتح", dark: "داكن" }
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: "en",
    interpolation: { escapeValue: false },
    detection: {
      order: ["localStorage", "navigator"],
      caches: ["localStorage"],
    },
  });

export default i18n;
